
#ifndef _MTCP_MEASURE_DEF_H_
#define _MTCP_MEASURE_DEF_H_

//#define _MTCP_MEASURE_SERVER_OVERALL_
//#define _MTCP_MEASURE_MTCP_READ_2_DPDK_READ_
//#define _MTCP_MEASURE_MTCP_WRITE_2_DPDK_WRITE_
//#define _MTCP_MEASURE_READ_
//#define _MTCP_MEASURE_WRITE_

//#define _MTCP_MEASURE_DPDK_SEND_
//#define _MTCP_MEASURE_DPDK_RECV_

#endif
